/**
 * Customer Service
 * 
 * Handles all HTTP communication with the Flask backend API for customer operations.
 * Provides methods for CRUD operations and hierarchical relationship queries.
 * 
 * @author Development Team
 * @date October 3, 2025
 * @version 1.0.0
 */

import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';

/**
 * Customer interface definition
 * 
 * Represents a customer entity with optional hierarchical relationships.
 * 
 * @property id - Unique identifier (auto-generated by backend)
 * @property name - Customer full name (required)
 * @property email - Customer email address (required, unique)
 * @property phone - Customer phone number (optional)
 * @property address - Customer physical address (optional)
 * @property entity_level - Classification: 'individual', 'entity', or 'corporate'
 * @property parent_id - Reference to parent customer ID (null for root-level)
 * @property parent_name - Resolved parent customer name (populated by backend)
 * @property children - Array of child customers (populated by hierarchy endpoint)
 */
export interface Customer {
  id?: number;
  name: string;
  email: string;
  phone?: string;
  address?: string;
  entity_level?: string;
  parent_id?: number;
  parent_name?: string;
  children?: Customer[];
}

/**
 * Customer Service Class
 * 
 * Injectable service provided at root level (singleton across the application).
 * Uses Angular's HttpClient for REST API communication.
 */
@Injectable({ providedIn: 'root' })
export class CustomerService {
  /** 
   * Base URL for customer API endpoints
   * NOTE: Change this to your production API URL when deploying
   */
  private apiUrl = 'http://localhost:5001/customers';

  /**
   * Constructor with HttpClient dependency injection
   * @param http - Angular's HTTP client for making requests
   */
  constructor(private http: HttpClient) {}

  /**
   * Retrieve all customers from the database
   * 
   * @returns Observable<Customer[]> - Array of all customer records
   * 
   * Example:
   *   this.customerService.getCustomers().subscribe(
   *     customers => console.log(customers)
   *   );
   */
  getCustomers(): Observable<Customer[]> {
    return this.http.get<Customer[]>(this.apiUrl);
  }

  /**
   * Retrieve a single customer by ID with direct children
   * 
   * @param id - Customer ID to retrieve
   * @returns Observable<Customer> - Customer object with children array
   * 
   * Example:
   *   this.customerService.getCustomer(1).subscribe(
   *     customer => console.log(customer.children)
   *   );
   */
  getCustomer(id: number): Observable<Customer> {
    return this.http.get<Customer>(`${this.apiUrl}/${id}`);
  }

  /**
   * Create a new customer record
   * 
   * @param customer - Customer object with required fields (name, email)
   * @returns Observable<{id: number}> - Response with newly created customer ID
   * 
   * Example:
   *   const newCustomer = {name: 'John Doe', email: 'john@example.com', entity_level: 'individual'};
   *   this.customerService.createCustomer(newCustomer).subscribe(
   *     response => console.log('Created customer with ID:', response.id)
   *   );
   */
  createCustomer(customer: Customer): Observable<{ id: number }> {
    return this.http.post<{ id: number }>(this.apiUrl, customer);
  }

  /**
   * Update an existing customer record
   * 
   * @param id - Customer ID to update
   * @param customer - Customer object with fields to update
   * @returns Observable<{message: string}> - Success message
   * 
   * Example:
   *   const updates = {name: 'Jane Doe', phone: '555-0102'};
   *   this.customerService.updateCustomer(1, updates).subscribe(
   *     response => console.log(response.message)
   *   );
   */
  updateCustomer(id: number, customer: Customer): Observable<{ message: string }> {
    return this.http.put<{ message: string }>(`${this.apiUrl}/${id}`, customer);
  }

  /**
   * Delete a customer record
   * 
   * @param id - Customer ID to delete
   * @returns Observable<{message: string}> - Success message
   * 
   * NOTE: Child customers will have their parent_id set to null.
   *       Consider handling orphaned children in production.
   * 
   * Example:
   *   this.customerService.deleteCustomer(1).subscribe(
   *     response => console.log(response.message)
   *   );
   */
  deleteCustomer(id: number): Observable<{ message: string }> {
    return this.http.delete<{ message: string }>(`${this.apiUrl}/${id}`);
  }

  /**
   * Get full hierarchical family tree for a customer
   * 
   * Returns complete ancestor chain (parents, grandparents, etc.) and
   * descendant tree (children, grandchildren, etc.) in a nested structure.
   * 
   * @param id - Customer ID to get hierarchy for
   * @returns Observable<any> - Object with customer, ancestors array, and descendants tree
   * 
   * Response structure:
   * {
   *   customer: {id, name, email, ...},
   *   ancestors: [{id, name, entity_level}, ...],  // Ordered root to parent
   *   descendants: [{id, name, entity_level, children: [...]}, ...]  // Recursive tree
   * }
   * 
   * Example:
   *   this.customerService.getCustomerHierarchy(3).subscribe(
   *     hierarchy => {
   *       console.log('Parents:', hierarchy.ancestors);
   *       console.log('Children:', hierarchy.descendants);
   *     }
   *   );
   */
  getCustomerHierarchy(id: number): Observable<any> {
    return this.http.get<any>(`${this.apiUrl}/${id}/hierarchy`);
  }
}
